id: A2ABC8728
title: f72C2
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:24:53.206062
  last_modified_at: 2022-05-27 19:24:53.206066
