id: A2ABC8728
title: fAD4F
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:24:53.217349
  last_modified_at: 2022-05-27 19:24:53.217351
